package mail

// Selection handles and apply receipts: a way to name a set of message ids
// once instead of transmitting it on every call that touches it.
//
// Bulk organization is a three-call shape — search, dry run, apply — and
// without handles all three carry the same id list, twice of it generated by
// the model rather than read. A handle replaces the second and third copies
// with a short token, and in doing so closes a safety gap the confirm phrase
// leaves open: the phrase binds count, destination and account, but not WHICH
// messages, so a preview of one set could confirm an apply of a different set
// the same size. A receipt cannot name a different set — it IS the set.
//
// The state this needs is deliberately the least durable kind that works:
// in-memory, per-process, TTL-bounded, capacity-bounded, and dropped whenever
// the service is rebuilt (which is to say whenever config changes). It never
// touches disk. Losing it costs one re-search, which every caller already
// handles; a handle that outlived the reasoning that produced it would be
// worse than no handle at all.

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"
	"sync"
	"time"
)

const (
	// handleTTL bounds a selection's or receipt's life. Long enough that a
	// search → preview → apply cycle never races it (observed at seconds),
	// short enough that a handle cannot be presented in a later stretch of
	// reasoning that has forgotten what it named.
	handleTTL = 15 * time.Minute
	// maxHandles bounds each kind independently. A 500-id selection is ~6 KB,
	// so the ceiling is well under a megabyte even when full.
	maxHandles = 64
)

// selection is a search's ordered id set, held so a mutating call can name it
// instead of repeating it.
//
// Deliberately absent: the search's filter and queryState. Binding a selection
// to queryState was the proposed way to detect a cohort that moved, but on a
// live mailbox queryState advances whenever ANY message arrives — the check
// would fire constantly for reasons unrelated to the named ids, and would need
// its own round trip to be a gate at all (methods in a JMAP batch run in
// order, so a query beside a set reports the state after it). What a receipt
// compares instead is each message's own placement; see receipt.Snapshot.
// Storing a queryState that nothing reads would only look like a guarantee.
type selection struct {
	ID        string
	AccountID string
	IDs       []string
	CreatedAt time.Time
}

// receiptKind distinguishes what a receipt authorizes, so a receipt minted by
// one tool's dry run cannot be presented to another's apply.
type receiptKind string

const (
	receiptMove  receiptKind = "move"
	receiptTrash receiptKind = "trash"
	receiptMark  receiptKind = "mark"
)

// receipt is a dry run's promise: this exact set, this exact operation. The
// apply presents it in place of both the ids and the confirm phrase, because
// the dry run that minted it already performed the preview the phrase exists
// to force.
type receipt struct {
	ID        string
	Kind      receiptKind
	AccountID string
	IDs       []string
	// Destination is the resolved mailbox for move/trash — resolved once, at
	// preview time, so a rename between preview and apply cannot silently
	// re-target the batch.
	DestID, DestName, DestPath string
	Keep                       bool
	Action                     string // mark only
	// Snapshot fingerprints each message's state as the preview saw it
	// (placement for move/trash, the target keyword for mark). Comparing it at
	// apply time detects the messages that moved underneath the caller — the
	// actual subjects, not merely the query they came from.
	Snapshot map[string]string
	// Selection records the selection slice the ids came from, when they came
	// from one, so the apply's result can describe itself as fully as the dry
	// run's did — including how much of the selection is left to work through.
	Selection *SelectionUse
	CreatedAt time.Time

	// inFlight guards against a second apply starting while the first is still
	// in the air; applied/result make a re-presentation after a lost result
	// replay the original outcome instead of repeating the work.
	inFlight  bool
	AppliedAt time.Time
	result    any
}

func (r *receipt) applied() bool { return !r.AppliedAt.IsZero() }

// handleStore holds live selections and receipts for one service instance.
type handleStore struct {
	mu         sync.Mutex
	selections map[string]*selection
	receipts   map[string]*receipt
	// now is time.Now in production; tests substitute a clock to exercise
	// expiry without sleeping.
	now func() time.Time
}

func newHandleStore() *handleStore {
	return &handleStore{
		selections: map[string]*selection{},
		receipts:   map[string]*receipt{},
		now:        time.Now,
	}
}

// newHandleID mints an opaque token. It is not a capability — the store is
// per-process and reachable only by this extension — so the randomness is
// hygiene against accidental collision and against a caller inferring one
// handle's name from another's, not a security boundary.
func newHandleID(prefix string) string {
	var b [6]byte
	if _, err := rand.Read(b[:]); err != nil {
		// crypto/rand does not fail in practice; a timestamp still yields a
		// unique-enough token rather than an empty one.
		return fmt.Sprintf("%s_%x", prefix, time.Now().UnixNano())
	}
	return prefix + "_" + hex.EncodeToString(b[:])
}

// putSelection stores an id set and returns its handle.
func (h *handleStore) putSelection(sel *selection) string {
	h.mu.Lock()
	defer h.mu.Unlock()
	sel.ID = newHandleID("sel")
	sel.CreatedAt = h.now()
	h.selections[sel.ID] = sel
	evict(h.selections, h.now(), func(s *selection) time.Time { return s.CreatedAt })
	return sel.ID
}

// getSelection returns a live selection, or an error naming why it is not
// usable. Expiry is reported as its own case: re-searching is the fix, and a
// caller told "expired" does not go looking for a bug.
func (h *handleStore) getSelection(id string) (*selection, error) {
	h.mu.Lock()
	defer h.mu.Unlock()
	sel, ok := h.selections[id]
	if !ok {
		return nil, fmt.Errorf("unknown selection %q — selections are held in memory for %s and are lost when the extension restarts; re-run email_search to mint a new one", id, handleTTL)
	}
	if h.now().Sub(sel.CreatedAt) > handleTTL {
		delete(h.selections, id)
		return nil, fmt.Errorf("selection %q expired (selections live %s) — re-run email_search to mint a new one", id, handleTTL)
	}
	return sel, nil
}

// putReceipt stores a dry run's promise and returns its handle.
func (h *handleStore) putReceipt(r *receipt) string {
	h.mu.Lock()
	defer h.mu.Unlock()
	r.ID = newHandleID("rcp")
	r.CreatedAt = h.now()
	h.receipts[r.ID] = r
	evict(h.receipts, h.now(), func(r *receipt) time.Time { return r.CreatedAt })
	return r.ID
}

// getReceipt returns a live receipt of the expected kind. A kind mismatch is
// its own message: presenting a move receipt to email_mark is a mistake worth
// naming precisely, not a generic refusal.
func (h *handleStore) getReceipt(id string, want receiptKind) (*receipt, error) {
	h.mu.Lock()
	defer h.mu.Unlock()
	r, ok := h.receipts[id]
	if !ok {
		return nil, fmt.Errorf("unknown receipt %q — receipts are held in memory for %s and are lost when the extension restarts; re-run the dry run to mint a new one", id, handleTTL)
	}
	if h.now().Sub(r.CreatedAt) > handleTTL {
		delete(h.receipts, id)
		return nil, fmt.Errorf("receipt %q expired (receipts live %s) — re-run the dry run to preview and mint a new one", id, handleTTL)
	}
	if r.Kind != want {
		return nil, fmt.Errorf("receipt %q was minted by a %s dry run and cannot be applied as a %s — re-run the dry run on the tool you mean", id, r.Kind, want)
	}
	return r, nil
}

// claimReceipt is the apply-side gate, taken before any network call. It
// returns the stored result when the receipt has already been applied (the
// caller lost the original result and is asking again), and otherwise marks
// the receipt in flight so a concurrent apply cannot double-submit.
func (h *handleStore) claimReceipt(r *receipt) (replay any, err error) {
	h.mu.Lock()
	defer h.mu.Unlock()
	if r.applied() {
		return r.result, nil
	}
	if r.inFlight {
		return nil, fmt.Errorf("receipt %q is already being applied — wait for that call to return rather than issuing a second one", r.ID)
	}
	r.inFlight = true
	return nil, nil
}

// releaseReceipt records the outcome of a claimed apply. On success the result
// is kept for replay; on failure the claim is simply dropped, because a failed
// move or mark is safe to retry — both are idempotent at the provider (setting
// mailboxIds or a keyword to a value it already holds is a no-op), so a retry
// after an ambiguous error costs nothing even if the first attempt did land.
func (h *handleStore) releaseReceipt(r *receipt, result any, err error) {
	h.mu.Lock()
	defer h.mu.Unlock()
	r.inFlight = false
	if err == nil {
		r.AppliedAt = h.now()
		r.result = result
	}
}

// evict drops expired entries, then the oldest surviving ones until the map is
// within capacity.
func evict[T any](m map[string]*T, now time.Time, createdAt func(*T) time.Time) {
	for id, v := range m {
		if now.Sub(createdAt(v)) > handleTTL {
			delete(m, id)
		}
	}
	if len(m) <= maxHandles {
		return
	}
	ids := make([]string, 0, len(m))
	for id := range m {
		ids = append(ids, id)
	}
	sort.Slice(ids, func(i, j int) bool {
		return createdAt(m[ids[i]]).Before(createdAt(m[ids[j]]))
	})
	for _, id := range ids[:len(m)-maxHandles] {
		delete(m, id)
	}
}

// --- snapshots ---

// placementKey fingerprints where a message currently lives, for the
// preview-versus-apply drift check on move and trash.
func placementKey(mailboxIDs map[string]bool) string {
	ids := make([]string, 0, len(mailboxIDs))
	for id, in := range mailboxIDs {
		if in {
			ids = append(ids, id)
		}
	}
	sort.Strings(ids)
	return strings.Join(ids, ",")
}

// keywordKey fingerprints whether a message already carries the keyword an
// email_mark run is about to set or clear.
func keywordKey(keywords map[string]bool, keyword string) string {
	if keywords[keyword] {
		return "set"
	}
	return "unset"
}

// driftedIDs lists the messages whose state at apply time differs from what
// the dry run recorded, in the receipt's own id order. Empty when the batch is
// exactly what was previewed.
func driftedIDs(snapshot map[string]string, order []string, current map[string]string) []string {
	var out []string
	for _, id := range order {
		was, previewed := snapshot[id]
		is, present := current[id]
		if !previewed || !present {
			// Absent now means notFound, which the result reports on its own
			// terms; absent then means the preview never saw it either.
			continue
		}
		if was != is {
			out = append(out, id)
		}
	}
	return out
}
