package mail_test

// A bulk-organization wave, end to end against the hermetic server, with its
// tool traffic measured in BOTH directions. The first field report put a
// 200-message archive batch at ~321KB of results and drove the projection and
// counts-only work; the second found that once results were cheap, the
// arguments were 88% of what was left — the same 200 ids sent to the search,
// then to the dry run, then to the apply, two of those three generated by the
// model rather than read.
//
// So this measures arguments alongside results, and runs the same wave twice:
// once naming ids outright, once naming them with a selection and a receipt.
// The ratio between the two is the property worth defending.

import (
	"context"
	"fmt"
	"strings"
	"testing"

	"terva-ext-jmap-mail/internal/jmaptest"
	"terva-ext-jmap-mail/internal/mail"
)

// maxWaveBytesPerMessage is the whole wave's tool traffic — every search, dry
// run, and apply, arguments and results both — divided by the messages
// organized, on the handle path. Fake ids are short (msg-N) where a real
// provider's are ~25 characters, so treat it as a regression tripwire rather
// than a promise.
const maxWaveBytesPerMessage = 40

// waveMeter accumulates what crossed the tool boundary in either direction.
type waveMeter struct {
	t     *testing.T
	bytes int
}

// sent counts a tool call's arguments, which on the bulk path are most of the
// cost and all of the model's output tokens.
func (m *waveMeter) sent(args map[string]any) { m.bytes += payloadSize(m.t, args) }

// received counts a tool result.
func (m *waveMeter) received(v any) { m.bytes += payloadSize(m.t, v) }

func seedWave(t *testing.T, total int) *mail.Service {
	t.Helper()
	srv := jmaptest.New()
	t.Cleanup(srv.Close)
	seed := srv.SeedStandard()
	for i := 0; i < total; i++ {
		srv.AddEmail(jmaptest.Email{
			MailboxIDs: []string{seed.InboxID},
			From:       []jmaptest.Address{{Name: "Newsletter Sender", Email: "news@example.test"}},
			Subject:    fmt.Sprintf("Weekly roundup %d — everything you missed", i),
			TextBody:   strings.Repeat("Newsletter body text that becomes a preview. ", 20),
			Keywords:   []string{"$seen"},
		})
	}
	return newStackService(t, srv, 0)
}

// runWave archives an inbox in batches, either retyping the ids into every
// mutating call or naming them once and referring to them afterwards.
func runWave(t *testing.T, total int, handles bool) (spent, organized int) {
	t.Helper()
	svc := seedWave(t, total)
	ctx := context.Background()
	m := &waveMeter{t: t}

	searchArgs := map[string]any{
		"mailbox": "inbox", "from": "news@example.test",
		"fields": []string{"id"}, "limit": 200,
	}
	for batch := 0; batch < 10; batch++ {
		m.sent(searchArgs)
		page, err := svc.Search(ctx, mail.SearchParams{
			Mailbox: "inbox", From: "news@example.test", Fields: []string{"id"}, Limit: 200,
		})
		if err != nil {
			t.Fatal(err)
		}
		m.received(page)
		if page.Returned == 0 {
			break
		}
		if page.SelectionID == "" {
			t.Fatal("search minted no selectionId — the handle path has nothing to name")
		}

		var dryParams mail.MoveParams
		var dryArgs map[string]any
		if handles {
			dryParams = mail.MoveParams{Selection: page.SelectionID, ToMailbox: "Archive", DryRun: true}
			dryArgs = map[string]any{"selection": page.SelectionID, "toMailbox": "Archive", "dryRun": true}
		} else {
			dryParams = mail.MoveParams{IDs: page.IDs, ToMailbox: "Archive", DryRun: true}
			dryArgs = map[string]any{"ids": page.IDs, "toMailbox": "Archive", "dryRun": true}
		}
		m.sent(dryArgs)
		dry, err := svc.Move(ctx, dryParams)
		if err != nil {
			t.Fatal(err)
		}
		m.received(dry)
		// Above the bulk threshold (20) the dry run owes the caller a phrase
		// and no enumeration; at or below it, the list is the answer and a
		// phrase is not required — so the loop stays correct for any `total`.
		if page.Returned > 20 && (dry.ConfirmPhrase == "" || len(dry.Moved) != 0) {
			t.Fatalf("bulk dry run should hand back a phrase and no enumeration: %+v", dry)
		}
		if dry.ReceiptID == "" {
			t.Fatal("dry run minted no receiptId")
		}

		var applyParams mail.MoveParams
		var applyArgs map[string]any
		if handles {
			// The receipt replaces the ids AND the phrase: the preview it came
			// from is the authorization.
			applyParams = mail.MoveParams{Receipt: dry.ReceiptID}
			applyArgs = map[string]any{"receipt": dry.ReceiptID}
		} else {
			applyParams = mail.MoveParams{IDs: page.IDs, ToMailbox: "Archive", Confirm: dry.ConfirmPhrase}
			applyArgs = map[string]any{"ids": page.IDs, "toMailbox": "Archive", "confirm": dry.ConfirmPhrase}
		}
		m.sent(applyArgs)
		applied, err := svc.Move(ctx, applyParams)
		if err != nil {
			t.Fatal(err)
		}
		m.received(applied)
		organized += applied.MovedCount
		if len(applied.Drifted) != 0 {
			t.Errorf("nothing else touched these messages, yet %d reported drift", len(applied.Drifted))
		}
	}
	if organized != total {
		t.Fatalf("organized %d of %d messages", organized, total)
	}
	return m.bytes, organized
}

func TestIntegrationBulkWavePayloadBudget(t *testing.T) {
	const total = 200

	withHandles, _ := runWave(t, total, true)
	withIDs, _ := runWave(t, total, false)

	if budget := total * maxWaveBytesPerMessage; withHandles > budget {
		t.Errorf("wave cost %d bytes of tool traffic for %d messages (%d B/message); budget is %d",
			withHandles, total, withHandles/total, budget)
	}
	// The point of handles: the ids cross once, not three times. Even with the
	// short fake ids — which understate the win, since a real provider's are
	// twice as long — naming the set should roughly halve the traffic.
	if withHandles*10 > withIDs*6 {
		t.Errorf("handle wave %d bytes vs id wave %d (%.0f%%) — expected at most 60%%",
			withHandles, withIDs, 100*float64(withHandles)/float64(withIDs))
	}
	t.Logf("200 messages: %d bytes naming a selection and a receipt, %d bytes retyping ids (%d vs %d B/message)",
		withHandles, withIDs, withHandles/total, withIDs/total)

	// The load-bearing comparison, and the one that survives id length
	// changing: the entire wave must cost less than a single unprojected page.
	svc := seedWave(t, 100)
	onePage, err := svc.Search(context.Background(), mail.SearchParams{Mailbox: "inbox", Limit: 100})
	if err != nil {
		t.Fatal(err)
	}
	if unprojected := payloadSize(t, onePage); withHandles >= unprojected {
		t.Errorf("the whole %d-message wave cost %d bytes; one unprojected 100-message page costs %d — the projection is not paying for itself",
			total, withHandles, unprojected)
	}
}

// The wave above never re-queries between batches, because moved mail leaves
// the inbox filter and the next search starts from position 0 either way. The
// signal that makes that discipline checkable is queryState, so pin it
// separately rather than letting it ride inside the budget test.
func TestIntegrationQueryStateMovesWithTheCohort(t *testing.T) {
	svc := seedWave(t, 30)
	ctx := context.Background()

	before, err := svc.Search(ctx, mail.SearchParams{Mailbox: "inbox", From: "news@example.test", Fields: []string{"id"}, Limit: 10})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := svc.Move(ctx, mail.MoveParams{Selection: before.SelectionID, ToMailbox: "Archive", DryRun: true}); err != nil {
		t.Fatal(err)
	}
	dry, err := svc.Move(ctx, mail.MoveParams{Selection: before.SelectionID, ToMailbox: "Archive", DryRun: true})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := svc.Move(ctx, mail.MoveParams{Receipt: dry.ReceiptID}); err != nil {
		t.Fatal(err)
	}
	after, err := svc.Search(ctx, mail.SearchParams{Mailbox: "inbox", From: "news@example.test", Fields: []string{"id"}, Limit: 1})
	if err != nil {
		t.Fatal(err)
	}
	if after.QueryState == before.QueryState {
		t.Errorf("queryState unchanged across a mutation (%q) — a paging caller cannot detect cohort drift", after.QueryState)
	}
}
